### PR TITLE
Allow alternate palettes for levels to be provided by images

### PR DESCRIPTION
**Pull request by Plombo**
Since .act is a Photoshop-specific format, it can be inconvenient for people without access to Photoshop. Supporting palette images as an alternative can hopefully make alternate level palettes more accessible.

### CODE REVIEW

**Comment by msmalik681** [comment]
Nice work

**Comment by DCurrent** [comment]
Honestly not a fan of this. Any image software worth its salt can work with and output .act. But if it really helps folks, so be it. 😊

**Comment by Plombo** [comment]
> Any image software worth its salt can work with and output .act.

This is absolutely not true, unless it's a weird way of saying that Photoshop is the only good image editing software. .act isn't a standard or widely known format at all. As far as I'm aware, there's no image editing software that reads and writes it besides Photoshop (and specialized programs designed for use with Mugen or OpenBOR).

**Comment by dbaldan** [comment]
@DCurrent I agree with @Plombo , but with a little comment: There are few programs which can open and save .act files, like Gimp or old stuff like Fireworks. But .ACT IS widely know and, in many cases, is the default color table format. There is .PAL too, but its order is reversed compared with .ACT.

Anyway, I don't think it will hurt to let people use images as palettes, specially when they can preview the palettes on their file manager if it's on an image format.

**Comment by DCurrent** [comment]
@Plombo no, it's not me trying to be a smarta** pushing Photoshop. I know .act is an Adobe thing, but yes, most of the more prolific imaging software out there works with it. It's the .pdf of color tables. Doesn't matter anyway, I approved your change before even commenting to begin with.

**Comment by Plombo** [comment]
> There are few programs which can open and save .act files, like Gimp or old stuff like Fireworks. But .ACT IS widely know and, in many cases, is the default color table format. There is .PAL too, but its order is reversed compared with .ACT.

As far as I can tell, Gimp can't read/write .act, just its own palette format (.gpl). But aside from that, @dbaldan, I see your point that .act is probably the most widely known type of color table file. My line of thinking was more that specialized "color table files" are so niche to begin with that none of the types are really "well known", and that's why few programs support .act.

**Pull request merged**
