### PR TITLE
Malik

### PR DESCRIPTION
**Pull request by msmalik681**
Android updates and added back platform compile tools for windows and wii.

### CODE REVIEW

**Review by DCurrent — CHANGES_REQUESTED** [review]
Changes to source are not necessary. One of them is already fixed and the other is a previously rejected magic number substitution for an issue that was also fixed. Make sure you have the latest global beta merged and that you're not overwriting fixes already in place please.

**Comment by msmalik681** [comment]
I did merge the latest global beta as you can see there are no updates to openbor.c and with the update to "collision_coordinates.c" I explained it [here](https://www.chronocrash.com/forum/index.php?threads/global-beta-issues-pre-4-0-release.5482/post-79121). the current global beta is still referencing z1 and z2.

**Comment by DCurrent** [comment]
I know about both issues and fixed them, we even discussed it in the forum. The commits are right here:

https://github.com/DCurrent/openbor/commit/ca7a5542bb9a6b90db720586fac07b10fbce0624

https://github.com/DCurrent/openbor/commit/e07f648398e1fda6ef6911fba72ae2e7c012a09e

I'm sorry, but I just can't accept this request as it is. Try a fetch, then pull from global beta. If that doesn't work then you will have to copy my changes manually.

**Comment by DCurrent** [comment]
Saw where you pulled down my changes. It's still not exact, but I'll pull them in. Thanks.

**Pull request merged**
