### PR TITLE
Kratus fixes(10 2021)

### PR DESCRIPTION
**Pull request by fgames9000**
# Pull Request
October-2021 Updates

## General Description
This pull request contains a mix of fixes and new features. Most of the additions have small codes and will not impact the engine too much, but add a lot of new customization options.

Translation
- Added an external location for translation files, outside of the PAK file in the folder "Translation/".
- Extended translation for level sets, you will need to add the same set names used in the levels.txt file to the translation.txt file by adding a new "msgid/msgstr".
- Made the translation function work during the "menu screen" to allow translation "on-the-fly".
- Moved the "menu" and "fonts" functions closer to the translation function during the OpenBOR startup.
- Small addition of a second instance of the "control_init" function to help translate control config menu.
- Revised the entire translation.txt file.

Blocking
- Fixed the "Blocking" instance during "non-blocking" animations (pain, walk, idle, etc).
- Fixed the "Blockodds" function to work properly according to the value defined on the entities.
- Fixed the "Toflip" function, now if the flag is 0 the "flash" will get the same direction as the defender.

Cheats
- Fixed some "Infinite health" cheat bugs ("in-hole" and "special attack" bugs).
- Made the "infinite health" cheat accessible by script using "openborvariant".
- This is readable only, not editable.
- Useful for scripts that need to know if the infinite health cheat is enabled before deduct some life during custom special moves.

Grabs and Vault
- Made "grabflip" property accessible by script.
- Made "grabdistance" accessible by script.  
- Added new backgrab animation.
- Added new vault animation.
- Added new vault2 animation.

Misc
- Fixed the "sleep" and "victory" animation bugs by fixing some issues related to the "idling" state.
- Added "combostyle" accessible by script.
- Increased maximum fonts from 10 to 20.
- Fixed the new broken code for the "disable" flag check on the "check_energy" internal function, back to the previous code. The new code doesn't allow the special moves to be used.
- Made the "shadow" property accessible by script
- Added the new "noshadow" property, can be changed at the entity header or by script. Useful to temporarily disable shadows without losing the previously defined shadow number after using "shadow 0". Useful to avoid using "fshadow" function at every animation, now can be disabled in any script event.

Special and Jumping attacks
- Fixed the wrong "jumpmovez" reference from X to Z. The old code points to the X axis but the function is used for the Z axis.  
- Added new "Ajspecial" flags to have more native "special attack" keys (flags 2,3 and 4 corresponds the a2, a3 and a4 keys).
- Added the new "jumpspecial" property that allows the modder to enable or disable the default animation movement.

By default, the "jumpspecial"animation "kills" the "xyz" movement while in the air, and now if this new property is used with the flag 1, the movement will not be killed, working the same as any jumping attack.

The native behaviour is maintained, old games don't need to change anything, this is useful for new games if the modder wants to use the "special3/jumpspecial" animation in a different way.

Can be edited by declaring at the entity header or by script using the "entity property".

- Fixed a bug in the "jumpspecial" that constantly consumes health or mp if the special button is constantly pressed, even if the current "jumpspecial" animation cycle is not finished yet.
- Fixed the noaircancel function bug, now the flag "2" works as intended and completely disables the cancelation between all jumping attacks.

In the previous code, both flags 1 and 2 have the same effect and allow the cancelation after last "jumpattack" is finished.

- Made the "noaircancel" function accessible by script using "openborvariant".

For backward compatibility, the models.txt native function works normally, but the scripted version will override the models.txt function if changed.
To edit it, you need to use "changeopenborvariant("noaircancel", value);".

NOTES:

The backgrab animation follows a similar form of other animations.
Ex: walk/backwalk, grab/backgrab.

The vault animations follow the same format and rules of all grab attacks.
Ex: grabup/grabup2, grabdown/grabdown2, vault/vault2.

The first vault can be automatically performed by pressing the jump button when an opponent is grabbed, and of course only when the animation is declared in the entity's file. Otherwise, the grabattack2 or attack3 will be performed by default.

The vault2 can only be used with scripts for now, but it's important to have because there's some differences between "front grab" and "back grab".

This new code maintains all previous functionality for backward compatibility. Vault animations don't have any predefined instance yet (aiflag, takeaction, etc), they are "empty" same as follow animations.

The focus is to give a proper native functionality for an important mechanic present in the entire SOR franchise (back grab and vault animations) and avoid losing some "follows" or "grabattacks" to make it happen.

When the jump button is pressed, the first vault animation will be prioritized over grabattack2 and attack3 animations, while grabbing an opponent. If there's no vault animation, the order is grabattack2 and then attack3. It means that the vault won't get in the way of the default system if it's not declared and will only be used when the modder knows what he is doing.

### CODE REVIEW

**Comment by DCurrent** [comment]
I'm a little concerned with the vault animations - OpenBOR had native Valuts once before. We removed them because there's just no way to make a 100% stable and universal vault without a lot of bloating additions, so that's better left to script.

I'll allow it though because I like most of the other changes. You've gone some great work here.

**Comment by fgames9000** [comment]
@DCurrent 

Thanks man! I totally agree with you about the vault and I understand why it was removed. I tried to split the process in two parts, one for the engine that contains only the necessary additions and the rest will be made with scripts.

In the SORX most of the backgrab/vault operations are done with scripts. The intention is to create a proper native animation for these features and make the process more simple and organized, avoiding the use of generic follows or grabattacks.

The first vault will work in a simple way same as any grabattack if no scripts are added. The character will play the vault animation once and release the opponent at the end. If the modder wants more features during the vault, he needs to develop his own code.

**Comment by msmalik681** [comment]
Great work that issue with losing all velocity when using jump to air cancel really annoyed me it was like the engine has predefined you have to use jump in air for a double jump but ignored it as it was easily overcome when using keyscripts.

**Comment by Darknior** [comment]
Incredible update, really, it will help a lot now to give users games in the good language :)
We can make the game in english for every one and give language files for users separately, i love the idea :)
Thanks a lot

**Comment by dbaldan** [comment]
nice work you have done here, buddy. Congrats!
The translation now will be easier to do and the losing velocity on air fix is very welcome.

**Pull request merged**
