### PR TITLE
Players refactor, 8 player support

### PR DESCRIPTION
**Pull request by Yukitty**
# Pull Request

## General Description
This pull request features sweeping changes to how individual players are handled, removing the static array initializers and fixed position values and replacing them with memset, loops, macros, and string formatting. As a result of these changes, it is now possible to have virtually unlimited players with minimal effort, thus I have doubled the max player limit to 8.

Please forgive the wild whitespace variations in my code, I wrote this with the wrong IDE setup and had to rebase it to prevent whitespace changes from completely flooding the commit.

If you'd prefer far less-than-sweeping changes and less-than-wild whitespace variations, I've also written a [basic 6 player version](https://github.com/Yukitty/openbor/tree/6p) which instead features the bare-minimum copy-pasting required to make players 5 and 6 function identical to the other 4.

I've only been able to test this with PC builds, so you'll have to let me know if other platforms contain something similar to SDL's joystick setup and need more adjustments. My apologies. :bowing_woman:

### CODE REVIEW

**Comment by DCurrent** [comment]
To be honest, I don't see much point in 8 player support, but I do like the code reworking. Let me take a closer look and get some of our port centric guys to tes. If there are no red flags I'll gladly approve and credit you. @plombo, mind giving this a test drive on the Wii?

**Comment by dbaldan** [comment]
I have mixed feelings about this. I think it's would be something cool to have in some specific cases, but I am afraid the maintenance of this could get harder to do. But is a cool idea.

Just a comment: you don't need to update the Xbox port, because it was dropped long time ago. I think we could even delete it from the code, kinda was made with the Dreamcast port

**Comment by Darknior** [comment]
Excellent good idea :)
Maybe not for current Beat'em up games ... but maybe for some other style like why not one day a Bomberman Game made with the OpenBOR engine :p 
Thanks

**Comment by Yukitty** [comment]
I made it because I have approximately 5 to 7 friends who want to play with me at any given time, and that newfangled Parsec thing makes playing OpenBOR with all of them possible.

I'd imagine this would work well if a supporting game used a widescreen resolution and put 3 players on top and 3 on the bottom. For now, players 5 through 8 are placed in a bit of an unfortunate stack covering more and more from the top of the screen by default, since I've been using the original BOR.PAK for testing purposes.

**Comment by dbaldan** [comment]
Indeed it would be great. But there are other things to consider, like the complete screen. How it works?

Also there is other things to consider, like the position of lifebars, credits, etc.

**Comment by Yukitty** [comment]
Nothing bad happens if you don't use it. :yum: Existing games with maxplayers set to 4 and below _should_ be unaffected. If you want to use it, it's your responsibility to figure out how you can use the screen space effectively.

**Comment by dbaldan** [comment]
That is not quite _true_ - you have to take care about things like the "complete screen" https://dcemulation.org/index.php?title=OpenBORManual#Hiscore_.26_Stage_complete

How it will work?

**Comment by Yukitty** [comment]
Ah, I might have missed some of those in my code, not entirely sure. :bowing_woman: I'll check again.

But the way those work is, it only reads in as many positions as you write, so if you're not using a player, you don't have to include its score and bonus positions.

**Comment by dbaldan** [comment]
Yes, I know, but if we will expand this, we need to at least fit those informations on the screen, because it's what OpenBOR already did on the past.

I would agree with you about the lifebar and such, but not about those information. Plus, the positions on complete screen are tied to the lifebar position (probably, to save some resources) and its a nightmare to change it - I did it myself some days ago and it was a huge pain.

**Comment by Plombo** [comment]
I'm a bit worried that this and the input rework will be Merge Conflict Central. That's not an argument against this change, though. It's my fault for taking so long to finish the input rework...

**Comment by Yukitty** [comment]
Ah. That sounds like a pain. Don't worry, if you want to push your input rework first I'll be perfectly happy to figure out how to rebase this and resolve all the conflicts myself. It's probably more important.

**Comment by Plombo** [comment]
Ah, thanks! I appreciate that. I'll try to get the input rework finished and merged before too long.

**Comment by guimabros** [comment]
marvelavengers - 0007
marvelavengers - 0077
did some tests and im so excited for this feature

**Comment by msmalik681** [comment]
That looks so cool.

**Comment by DCurrent** [comment]
@Plombo still waiting for your final word on this update. Will it conflict with your control fixes?

**Comment by Yukitty** [comment]
(Rebased to current master.)

**Comment by DCurrent** [comment]
@Plombo this had another refactoring. Mind having a look please?

**Comment by guimabros** [comment]
https://www.twitch.tv/videos/798629907

did some playtest with the 8 players the player 5 have wrong  xy values i had to do some extra math to find the real value of his x position

**Comment by DCurrent** [comment]
Sorry, but @Plombo also has a very large control reading project going that predates yours. Until I get an OK from from, I will not accept this into the main code. I spoke with him not too long ago and he is still active. Hopefully we'll get word soon.

**Comment by adamaxis** [comment]
Dang, I hope this makes it through. My friend-group rage-quit OpenBOR over how terribad the controller configuration system is. The controller configuration process is like rocket science: I spent about 2 hours sitting on a couch with my annoyed friends trying to figure it out why it swapped controllers and buttons in 4-player mode when you pass the game menu.

**Comment by DCurrent** [comment]
After further review, I have decided to reject this request indefinitely. I really appreciate the idea, but the risk to reward isn't there right now. There are just too many other large (and conflicting) changes already in the works that predated this request, including a control fix that we recently merged to the main source and will be included in an upcoming release.

**Comment by Darknior** [comment]
I really wish @Yukitty will found a solution to update or rebase his code for 8 players.
I have an idée and plan to release a game, but a game like Bomberman, and 4 players is not enough :(

**Pull request closed without merging**
