### PR TITLE
Taco dog

### PR DESCRIPTION
**Pull request by TacoDog311**
# Pull Request

## General Description
Makefile fixes for GCC 9 compilations
Vita compilation fixes
Added a new cheat for instant kills

### CODE REVIEW

**Comment by Darknior** [comment]
Excellent, i love the new cheat for instant kills :)
It will help to save time when trying games for fix, thanks

**Comment by DCurrent** [comment]
Not sure I'm ok with this. Your pull request is really messy... nearly 40 commits that are already in the source code. Also from what I can tell, the Gcc9 fix is just suppressing errors rather than fixing the cause. I'll need to review this a bit more.

**Comment by TacoDog311** [comment]
> Not sure I'm ok with this. Your pull request is really messy... nearly 40 commits that are already in the source code. Also from what I can tell, the Gcc9 fix is just suppressing errors rather than fixing the cause. I'll need to review this a bit more.

I agree actually with the mess, the compiler fixes are admittedly hacky.  But which commits are already in the source?

Perhaps I should separate out the new cheat, which I think is cleaner and useful for debugging.

**Comment by DCurrent** [comment]
That's probably for the best. If you submit a commit that just has the cheat, I should be able to include it,

**Pull request closed without merging**
