### PR TITLE
fixing mallinfo for glibc 2.33+

### PR DESCRIPTION
**Pull request by msmalik681**
Added mallinfo2 for Linux distros running glibc 2.33+

Would appreciate it if @Plombo could review to make sure everything is ok.

### CODE REVIEW

**Comment by msmalik681** [comment]
@DCurrent  I think this should be fine to add and it will only effect the Linux port if Plombo has any issues we can change later.

**Comment by DCurrent** [comment]
@msmalik681, I had to revert this. After a second check, it fails to compile (missing features.h error).

**Comment by Plombo** [comment]
I really thought I did this a year or two ago. Apparently not! Anyway, seems good aside from the build issue where features.h is being included on platforms that don't have it.

**Comment by msmalik681** [comment]
Yeah figured that was the issue i should be able to quick fix this tomorrow

**Comment by msmalik681** [comment]
@Plombo not complete sure on how to wrap features.h would be  ?

#ifdef __GLIBC__
#include <features.h>
#endif

or maybe ?

#ifndef WIN
#include <features.h>
#endif

or possibly ?

#ifdef LINUX
#include <features.h>
#endif

**Pull request merged**
