### PR TITLE
Sprite loading improvements

### PR DESCRIPTION
**Pull request by Plombo**
Two minor improvements to the process of loading sprites. They don't make a huge impact on loading times, since loading is mostly bound to I/O speed, but they are still improvements.

### CODE REVIEW

**Comment by dbaldan** [comment]
@Plombo so maybe this was the reason that png files do load slower than gif files. I've experienced a significant load time improvement when I changed from PNG to GIF on my mod.

**Comment by Plombo** [comment]
@dbaldan Sadly, it's not. That's what I was going for when I made the PNG loading change, but I tested it and found that PNG files still load slower.

**Comment by msmalik681** [comment]
Great job @plombo. I have tested and found even if a png is smaller physical size the used ram is exactly the same as a gif so I have switched too.

I think the png has image data that is then compressed so it has to be extracted before saved in memory that would explain the longer loading times.

I was thinking not sure if this can be done but if we could use 16 color pngs they make a big difference in size so if you reference a 256 colour palette and the first 16 colors match could that work?  I am always looking for ways to save memory sorry.

**Comment by Plombo** [comment]
@msmalik681 GIFs have to be decompressed, too. I think the problem is more likely the code being used to read the image from the packfile. I have an idea about another possible way to improve PNG loading speed.

About the 16 color PNGs, I believe you're thinking too hard about saving memory on sprites. OpenBOR's memory usage for sprites is actually already very good, so we don't need to find ways to  improve it.

**Comment by dbaldan** [comment]
@msmalik681 do not use compressed PNG for that. It increases the load time.

**Comment by DCurrent** [comment]
Also, there are other reasons to use .png besides file size. I don't want to get into that here. Since .png and .pcx were both around at BOR's inception, I'm kind of surprised .gif was the format of choice then, but I'm sure there were reasons. But that was 10+ years ago. These days it's not worth converting old modules to .png, but for WIPs you should stay with 8-bit, non-interlaced .png files.

**Comment by DCurrent** [comment]
@msmalik681 there are other reasons to use .png besides file size. I don't want to get into that here. I'm kind of surprised .gif was the format of choice then. They didn't standardize .png until late 2003, and by then BOR was pretty much finished, but .pcx was around and proven. Thing is, that was 10+ years ago. These days .png is the truth. It's not worth converting old modules to .png, but for WIPs you should stay with 8-bit, non-interlaced .png files.

**Comment by Plombo** [comment]
There are reasons to use PNG over GIF besides file size? That's news to me. I know you just said you didn't want to get into that here, but now I'm curious.

**Pull request merged**
