### PR TITLE
Build Numbers

### PR DESCRIPTION
**Pull request by msmalik681**
Added option to add build numbers to be read from build_number.h and apply to all versions including the exe file.  There is no automated process if you want to add a build number update the file "build_number.h" file before you compile.

Updated android default output filename.  Fixed path's to android apk to compile with other releases.

Added myself to openbor credits.

Updated gitignore to only ignore extracted folders and files from the tools directory after building the engine.

### CODE REVIEW

**Comment by Plombo** [comment]
Why make it this complicated? There's no need for this "build_number.h" business. The existing code and build system will already put the correct build numbers as long as the git executable is in your command line PATH. It does for me on Linux, anyway, and even if for some reason it doesn't work on Windows, it probably just needs some small fix there.

**Comment by msmalik681** [comment]
The build_numbers.h file applys the build number to the windows exe and version.sh if we miss out updating the details for the exe the current process is fine.

**Comment by Plombo** [comment]
I don't think we're on the same page here. I don't understand what you mean by "the current process is fine".

**Comment by msmalik681** [comment]
Sorry let me explain Openbor.exe uses a .res file for its file information (when you right click on windows exe and select properties) I have added building the .res file into the build process and it applies the build number from build_number.h and adds its to the .res file so the exe also has build information.  I also set version.sh to get build number from build_number.h file.

**Comment by Plombo** [comment]
It's cool if you want to add the build number to the .res, but why have this new build_number.h that has to be manually updated? Why can't we just continue to get the build number with `git rev-list --count HEAD` and write it to version.h, like we do in current git master? If you need to \#include a header with the build number, why not just include version.h, where the build number has always been?

**Comment by msmalik681** [comment]
Ok i will update using your recomendations.  Can you help with one thing I cant windres.exe to run in vershion.sh without stopping the build process but it works in build.sh any idea what I am doing wrong ?

**Comment by Plombo** [comment]
Does it give you any kind of error message?

**Comment by msmalik681** [comment]
I can not remember right when I hit that roadblock again I will pm you the details if that is ok.

**Pull request closed without merging**
