### PR TITLE
Entity Property Exposure

### PR DESCRIPTION
**Pull request by DCurrent**
This update encompasses ~300 separate commits and represents the first major milestone in script and property access revamp:

- **All** members of the entity structure are now exposed through `get_entity_property(pointer <entity>, string <property>);` and `set_entity_property(pointer <entity>, string <property>, mixed <value>);` functions. [Each and every exposed property is fully documented in the Openbor Wiki](http://www.chronocrash.com/apps/wiki/obor/index.php?title=Entity_Property_(Scripting)).
- "Fake" properties (i.e. model properties in guise of entity properties, horizontal growth sub-properties, etc.) are NOT exposed. Pointers to these sub sets are made available instead, where their exposure can be handled by dedicated functions (in progress).
- Entity structure is reorganized by member data type to eliminate as much memory slop as possible. 
- Where possible, entity structure data types converted to bool, unsigned int, or enumerator to reduce memory consumption and improve readability.
- Some blags combined and / or bit masked.
- Numerous internal functions re-tooled or re-written outright to improve readability or functionality.
- Memory footprint of individual entities reduced by ~450 bytes each.
- Magic numbers replaced with exposed constants when encountered.

### CODE REVIEW

**Comment by dbaldan** [comment]
@DCurrent wow, congrats for such great work! There are some great stuff there, like previous anim.
I have just a question - since you exposed BLAST to script, there is any chance to fix its knockdown bug?
http://www.chronocrash.com/forum/index.php?topic=3482.msg48043#msg48043

**Comment by Plombo** [comment]
I know you're the lead developer, but hopefully you won't mind me complaining a bit: 300+ commits is *way* too many, even for a change of this size. It should be like 30 commits at most.

At a glance, it looks like a lot of the commits in that history are fixes for compiler errors and untested new code. In general, anyone should be able to `git checkout` any commit in the git history and have the application compile and work properly. If compiling and testing your changes before every commit feels too cumbersome, it means you're using too many commits to express your changes.

A tip for making better commit histories: if you find that you messed something up in your most recent commit, just do `git reset HEAD^`, fix the mistake, and do `git commit` with the fixed version. The great thing about having your version history stored locally is that you can go back and edit mistakes out!

**Comment by DCurrent** [comment]
Obviously I don't mind complaints (well, not well thought ones like yours anyway :P). But that said I'm not sure why the number of commits is an issue. That's what branches were for. As I work on a branch, I commit little updates as a I go. Mostly because of the following:

- I like the idea of small commits because if I do something stupid, its easy to revert that one change instead of probing through a huge single commit, testing, and then hand editing until the problem is gone. As is, it's a pain to sort through micro-commits too, but a bit of heuristic logic quickly narrows the search (same logic as a database). Once you do find the bad commit, it's much simpler to fix. 
- At least for me, it really, REALLY helps the workflow. Between work, school, etc. and my own ADHD, getting pulled away from a large in progress commit pretty much ruins the work instantly for me. Notes and such don't help much - my mind just works a certain way, and it's nearly impossible for me to come back and resume something. Before Github, I can't tell you how many times I had to scrap a ton of work and just start over. Not just for OpenBOR, but a lot of my module projects and other things too.
- Compatibility. By inching along bits at a time and working on my branch, I don't risk having to retool a big change that could break or be broken by something one of you are working on.

Anyway, as said above my logic is that I set up a branch based on a milestone. Entity properties for instance. Then I just make small updates until it's ready, pull any updates from other branches down if necessary, and pull request my branch. I kind of thought that was the point of branches and just don't really see a better way to do it. Why a limit to number of smaller commits in a branch? Can you elaborate?

**Comment by Plombo** [comment]
Okay, I see where you're coming from with how very small commits help your workflow. There's nothing wrong with using small commits in your local repository. But there are two problems with merging tons of tiny commits like that into the master branch.

The first is it makes the version history illegible. Legible version history is important for finding and fixing bugs without regressing anything. If I'm trying to find the cause of a bug, and a `git blame` or `git bisect` leads me somewhere in the middle of those 300+ commits, I'm going to have a hard time understanding the change or why it was made if there's no clear context for it in the version history. And if I can't understand a change that caused an issue, any fix to the issue will run the risk of regressing something else.

Speaking of `git bisect`, bisect is the other problem, and the biggest reason why the repository needs to compile and work correctly at every commit. I could be bisecting a regression completely unrelated to your entity property changes, but the bisect command can still decide to stop on a commit like 547d3a5dff2f84c along the way, where the mapstrings enum has been updated but the string array hasn't yet, so the script function is broken. I might not be able to test the bug I'm actually looking for because of that new breakage.

Maybe that particular commit isn't the best example if recursive damage is a new feature, but you get the idea - breaking things and immediately fixing them causes problems with `git bisect`.

New suggestion: Since making small commits helps your workflow, maybe you could make small commits like you've been doing, but as you reach points where it's logical to do so, compile and test your changes, and then [squash](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) your last several commits together into a larger, more significant commit. If you do that, git will even put your old commit messages into the squashed commit message, so you won't lose your more granular progress records.

**Pull request merged**
