### PR TITLE
Maliks build numbers

### PR DESCRIPTION
**Pull request by msmalik681**
Automated build numbers added so now source code will include physical build number when engine compiled.

### CODE REVIEW

**Comment by dbaldan** [comment]
@msmalik681 really thank you for that. This is very useful.

**Comment by DCurrent** [comment]
After reading the post at Chronocrash, I have some serious concerns about the added complexity this creates, especially for merging vs. direct commits. @Plombo what are your thoughts?

**Comment by msmalik681** [comment]
Hey @DCurrent ust wanted to say there is a small chance of 2 simultaneous pull request I cant say I have ever seen 2 open but I understand your concers.  I am not happy that git hooks only work on a local level.

I would like to see what @Plombo has to say but I also want to suggest a alternative.  The releases have always been made manually so how about manually updating the build number for releases we can still debug as releases reference a commit they were bases on.

**Comment by msmalik681** [comment]
I will update for a manual process.

**Comment by Plombo** [comment]
Why can't we just update the get_revnum function in version.sh to remove the SVN references and just use `git rev-list --count HEAD`? That's how the build numbers were "automated" back in the SVN days, and it worked just fine. No hooks or pull request tapdancing required.

**Comment by msmalik681** [comment]
So when you compile it will the master commit count is added to the build number ?

**Comment by Plombo** [comment]
The commit count on the current (local) branch is used as the build number; nothing has to be "added".

**Pull request closed without merging**
