### PR TITLE
64-bit capable + improvements for Android

### PR DESCRIPTION
**Pull request by haxpor**
# Pull Request

## General Description
First of all, thanks to @msmalik681 to notify me about [upcoming enforced requirement](https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html) (coming in August 2019) pushing by Google for all apps to be 64-bit compatible. I checked up, OpenBOR is still bundled with pre-built 32-bit libraries. This PR will clear such issue +  improvements for android.

## Summary of Changes
* Updated all pre-built deps of Android. We're green for 32/64 bit build for Android.
* Updated SDL2 backend stepping closer to newer although it's still 10 months old from the tip upstream.
  >With this, Android's native platform support is updated. No need to modify `SDLActivity.java` which belongs to upstream anymore, we have our own `GameActivity.java` inherited functionality from former with migrated platform support previously had done by UTunnels, CRxTRDude, White Dragon, and @msmalik681 although modified or removed as need as upstream has better support.
* Fixed alignment of touchpad vibration to be center
* Touchpad vibration feature is optimized, and modified to vibrate shorter.
* Minor fixes and update for keystore script (comment), and README update; all for Android.

(*Additional information is below*)

---

## Pre-built 64-bit libraries
Total size is 45 MB (of this pre-built directory) as for this spanning into 2 architectures `arm64-v8a` and `armeabi-v7a` built for release build + debug-info. The latter plays key role in increased size.

### Note
* Checked, and tested on real device Huawei G9 lite for both debug and release build with a single architecture built (to see if `arm64-v8a` alone works), or both. All green.
* I will write a post about this process similar to [Cross-Compile OpenBOR engine](https://wiki.abzi.co/openbor-wiki/posts/crosscompile.html) as shared in forum, and come up with automated script later; at least we will have an ease of way to quickly build all deps for Android when needed and have reference to go back to.

### CODE REVIEW

**Comment by msmalik681** [comment]
Thanks this was above my level to add.  So the apk file is now 45MB that leaves 55MB for the apk that kind of sucks.

**Comment by haxpor** [comment]
@msmalik681 it doesn't add up like that actually. Final .apk for OpenBOR app is 3.6 MB for release build, and 3.9 MB for debug build. The size shown for dependencies you see will be stripped automatically by gradle.

**Comment by dbaldan** [comment]
@haxpor question: is there a way to change the "stretch to screen" option to accept non 16:9 resolutions?
I have a more wider phone (uses 18:7) resolution and some apps accepts it - some will try to stretch, some will accept pinch command to make it to strecth

**Comment by haxpor** [comment]
@dbaldan nice for you to report this. I quickly checked the code and it should work for any screen (if i'm not wrong). Would you please create another issue with attached screenshot, I'll take a look. Thanks!

**Pull request merged**
