### PR TITLE
update.me

### PR DESCRIPTION
**Pull request by msmalik681**

### CODE REVIEW

**Comment by DCurrent** [comment]
I don't understand what you're trying to do here @msmalik681. It says you want to merge from the Master into your own branch - you don't need to create a pull request for that. Pull requests are only required when you want to push your branch to the master. Let me know exactly what it is you are trying to accomplish and I'll give you a hand.

**Comment by msmalik681** [comment]
I thought I have to pull all the latest changes from master then update my branch then pull back to master.  If there is a better way to get updates from master to my branch please share.

**Comment by dbaldan** [comment]
@msmalik681 simply delete your branch and create one.
By the way, DC has explained that its not a good idea to name it "USER branch", but name it using your project. For example, mine was called "debug-menu" because is what I were working on.

This will help other devs to understand what you are working on.

**Comment by DCurrent** [comment]
To elaborate, when you want to start a new project you just create a branch from Master and away you go. If the Master is updated while still you are working on your branch, then you just perform a merge from Master. It's not a requirement, but I always like to do it to makes sure whatever I'm working on is in line with the latest from everyone else.

No special permissions or pull requests are required to merge **from** Master or any other branch. The only restriction is merging **to** Master. That's when you need to make a pull request.

HTH. When I get a chance I'll write up a tutorial in the forum.

**Comment by msmalik681** [comment]
Very helpful thanks.

**Pull request closed without merging**
